### ISSUE TITLE
生成时出现报错

### ISSUE THREAD

**Issue by Dream-Rainy** [xszqxszq/5000choyen-mirai#1]
系统版本：Ubuntu 18.04.4 LTS
java版本：
> openjdk version "11.0.14.1" 2022-02-08
>OpenJDK Runtime Environment (build 11.0.14.1+1-Ubuntu-0ubuntu1.18.04)
>OpenJDK 64-Bit Server VM (build 11.0.14.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

MCL版本：iTXTech Mirai Console Loader version 2.0.0-beta.2-c77173e
mirai版本：2.10.1
日志：
```
2022-04-16 11:06:21 E/main: Exception in coroutine <unnamed>
java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-amd64/lib/libawt_xawt.so
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at java.desktop/java.awt.image.ColorModel$1.run(ColorModel.java:209)
        at java.desktop/java.awt.image.ColorModel$1.run(ColorModel.java:207)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.image.ColorModel.loadLibraries(ColorModel.java:206)
        at java.desktop/java.awt.image.ColorModel.<clinit>(ColorModel.java:219)
        at java.desktop/java.awt.image.BufferedImage.<clinit>(BufferedImage.java:286)
        at com.soywiz.korim.format.AwtNativeImageFormatProvider.create(NativeImageFormatProviderJvm.kt:42)
        at com.soywiz.korim.bitmap.NativeImageKt.NativeImage(NativeImage.kt:74)
        at com.soywiz.korim.bitmap.NativeImageKt.NativeImageOrBitmap32(NativeImage.kt:72)
        at com.soywiz.korim.bitmap.NativeImageKt.NativeImageOrBitmap32$default(NativeImage.kt:71)
        at xyz.xszq.FiveThousandChoyen.generate(FiveThousandChoyen.kt:29)
        at xyz.xszq.FiveThousandChoyenPlugin.handle(FiveThousandChoyenPlugin.kt:83)
        at xyz.xszq.FiveThousandChoyenPlugin.access$handle(FiveThousandChoyenPlugin.kt:38)
        at xyz.xszq.FiveThousandChoyenPlugin$onEnable$2$1$1$1.invokeSuspend(FiveThousandChoyenPlugin.kt:67)
        at xyz.xszq.FiveThousandChoyenPlugin$onEnable$2$1$1$1.invoke(FiveThousandChoyenPlugin.kt)
        at xyz.xszq.FiveThousandChoyenPlugin$onEnable$2$1$1$1.invoke(FiveThousandChoyenPlugin.kt)
        at xyz.xszq.FiveThousandChoyenPluginKt.requireNot(FiveThousandChoyenPlugin.kt:137)
        at xyz.xszq.FiveThousandChoyenPluginKt.access$requireNot(FiveThousandChoyenPlugin.kt:1)
        at xyz.xszq.FiveThousandChoyenPlugin$onEnable$2$1$1.invokeSuspend(FiveThousandChoyenPlugin.kt:66)
        at xyz.xszq.FiveThousandChoyenPlugin$onEnable$2$1$1.invoke(FiveThousandChoyenPlugin.kt)
        at xyz.xszq.FiveThousandChoyenPlugin$onEnable$2$1$1.invoke(FiveThousandChoyenPlugin.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$startsWithImpl$2.invokeSuspend(messageSubscribersInternal.kt:58)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$startsWithImpl$2.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$startsWithImpl$2.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invokeSuspend(messageSubscribersInternal.kt:27)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invokeSuspend(subscribeMessages.kt:253)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:455)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:50)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:50)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(InternalEventListeners.kt:166)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.access$process(InternalEventListeners.kt:1)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$2$1.invokeSuspend(InternalEventListeners.kt:132)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Dream-Rainy** [comment]
看起来像是我的java的问题，（java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-amd64/lib/libawt_xawt.so）
重新安装后就完事了
